---

packs:
  - pack: wordpress
    values:
      mysql:
        image:
          repository: mysql # format: registry.custom.com/me/my_image || me/my_image || myimage
          tag: "5.6"
          tag_pattern: "glob:5.*"
        root_password: changemeroot
      wordpress:
        image:
          repository: wordpress
          tag: latest
      user: wp
      password: changeme
      database: wordpress

  - pack: incubator/swarm-sync
    values:
      swarm_sync_yml: |
        swarm-sync:
          stacks:
            - nonprod
          updateInterval: 300000 # 5 minutes
          git:
            url: https://github.com/kevb/swarm-sync-example
            branch: master
          docker:
            socketPath: /var/run/docker.sock


  - pack: incubator/portainer