---
version: '3.3'

services:
  portainer:
    image: "{{ image.repository }}:{{ image.tag }}"
    deploy:
      labels:
        - "swarm-sync.managed=true"
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
      placement:
        constraints:
          - node.role == manager
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock