---
version: '3.3'

services:
  swarm-sync:
    image: "{{ image.repository }}:{{ image.tag }}"
    volumes:
      - swarm_sync_storage:/run/swarm-sync
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "swarm-sync.managed=true"
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
      placement:
        constraints:
          - node.role == manager
    secrets:
      - source: {{ secret_from_file("swarm-sync.yml") }}
        target: /etc/swarm-sync.yml

volumes:
  swarm_sync_storage: {}